<?xml version='1.0' encoding='UTF-8'?>
<tileset version="1.10" name="NPC3 - CrouchIdle" tilewidth="128" tileheight="128" tilecount="120" columns="15">
  <image source="../../Fantasy tileset - 2D Isometric/Characters/NPC3/CrouchIdle.png" width="1920" height="1024" />
  <tile id="0">
    <animation>
      <frame tileid="0" duration="80" />
      <frame tileid="1" duration="80" />
      <frame tileid="2" duration="80" />
      <frame tileid="3" duration="80" />
      <frame tileid="4" duration="80" />
      <frame tileid="5" duration="80" />
      <frame tileid="6" duration="80" />
      <frame tileid="7" duration="80" />
      <frame tileid="8" duration="80" />
      <frame tileid="9" duration="80" />
      <frame tileid="10" duration="80" />
      <frame tileid="11" duration="80" />
      <frame tileid="12" duration="80" />
      <frame tileid="13" duration="80" />
      <frame tileid="14" duration="80" />
      <frame tileid="15" duration="80" />
      <frame tileid="16" duration="80" />
      <frame tileid="17" duration="80" />
      <frame tileid="18" duration="80" />
      <frame tileid="19" duration="80" />
      <frame tileid="20" duration="80" />
      <frame tileid="21" duration="80" />
      <frame tileid="22" duration="80" />
      <frame tileid="23" duration="80" />
      <frame tileid="24" duration="80" />
      <frame tileid="25" duration="80" />
      <frame tileid="26" duration="80" />
      <frame tileid="27" duration="80" />
      <frame tileid="28" duration="80" />
      <frame tileid="29" duration="80" />
      <frame tileid="30" duration="80" />
      <frame tileid="31" duration="80" />
      <frame tileid="32" duration="80" />
      <frame tileid="33" duration="80" />
      <frame tileid="34" duration="80" />
      <frame tileid="35" duration="80" />
      <frame tileid="36" duration="80" />
      <frame tileid="37" duration="80" />
      <frame tileid="38" duration="80" />
      <frame tileid="39" duration="80" />
      <frame tileid="40" duration="80" />
      <frame tileid="41" duration="80" />
      <frame tileid="42" duration="80" />
      <frame tileid="43" duration="80" />
      <frame tileid="44" duration="80" />
      <frame tileid="45" duration="80" />
      <frame tileid="46" duration="80" />
      <frame tileid="47" duration="80" />
      <frame tileid="48" duration="80" />
      <frame tileid="49" duration="80" />
      <frame tileid="50" duration="80" />
      <frame tileid="51" duration="80" />
      <frame tileid="52" duration="80" />
      <frame tileid="53" duration="80" />
      <frame tileid="54" duration="80" />
      <frame tileid="55" duration="80" />
      <frame tileid="56" duration="80" />
      <frame tileid="57" duration="80" />
      <frame tileid="58" duration="80" />
      <frame tileid="59" duration="80" />
      <frame tileid="60" duration="80" />
      <frame tileid="61" duration="80" />
      <frame tileid="62" duration="80" />
      <frame tileid="63" duration="80" />
      <frame tileid="64" duration="80" />
      <frame tileid="65" duration="80" />
      <frame tileid="66" duration="80" />
      <frame tileid="67" duration="80" />
      <frame tileid="68" duration="80" />
      <frame tileid="69" duration="80" />
      <frame tileid="70" duration="80" />
      <frame tileid="71" duration="80" />
      <frame tileid="72" duration="80" />
      <frame tileid="73" duration="80" />
      <frame tileid="74" duration="80" />
      <frame tileid="75" duration="80" />
      <frame tileid="76" duration="80" />
      <frame tileid="77" duration="80" />
      <frame tileid="78" duration="80" />
      <frame tileid="79" duration="80" />
      <frame tileid="80" duration="80" />
      <frame tileid="81" duration="80" />
      <frame tileid="82" duration="80" />
      <frame tileid="83" duration="80" />
      <frame tileid="84" duration="80" />
      <frame tileid="85" duration="80" />
      <frame tileid="86" duration="80" />
      <frame tileid="87" duration="80" />
      <frame tileid="88" duration="80" />
      <frame tileid="89" duration="80" />
      <frame tileid="90" duration="80" />
      <frame tileid="91" duration="80" />
      <frame tileid="92" duration="80" />
      <frame tileid="93" duration="80" />
      <frame tileid="94" duration="80" />
      <frame tileid="95" duration="80" />
      <frame tileid="96" duration="80" />
      <frame tileid="97" duration="80" />
      <frame tileid="98" duration="80" />
      <frame tileid="99" duration="80" />
      <frame tileid="100" duration="80" />
      <frame tileid="101" duration="80" />
      <frame tileid="102" duration="80" />
      <frame tileid="103" duration="80" />
      <frame tileid="104" duration="80" />
      <frame tileid="105" duration="80" />
      <frame tileid="106" duration="80" />
      <frame tileid="107" duration="80" />
      <frame tileid="108" duration="80" />
      <frame tileid="109" duration="80" />
      <frame tileid="110" duration="80" />
      <frame tileid="111" duration="80" />
      <frame tileid="112" duration="80" />
      <frame tileid="113" duration="80" />
      <frame tileid="114" duration="80" />
      <frame tileid="115" duration="80" />
      <frame tileid="116" duration="80" />
      <frame tileid="117" duration="80" />
      <frame tileid="118" duration="80" />
      <frame tileid="119" duration="80" />
    </animation>
  </tile>
</tileset>